TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += transtec.db
DATA += transtec.proto

#=======================================
include $(TOP)/configure/RULES
